# Generated by Django 5.1.1 on 2024-10-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(default='active', max_length=100)),
                ('role', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=15)),
                ('emergency_contact', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=5)),
                ('nationality', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('marital_status', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=15)),
            ],
        ),
    ]
