# Generated by Django 5.1.1 on 2024-10-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=255)),
                ('religion', models.CharField(max_length=255)),
                ('marital_status', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=10)),
            ],
        ),
    ]
