# Generated by Django 5.1.1 on 2024-10-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_personalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_name', models.CharField(max_length=100)),
                ('primary_relationship', models.CharField(max_length=100)),
                ('primary_phone', models.CharField(max_length=15)),
                ('secondary_name', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
